[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes="1.5.0"
futures="0.3"
sqlite="0.31"
crossbeam="0.8"
colored = "2.1.0"